### ISSUE TITLE
Under what licence is pysed distributed?

### ISSUE THREAD

**Issue by deragon** [mahmoudadel2/pysed#1]
Under what licence is pysed distributed?  This should be documented in the README.md file and in the code.

**Comment by mahmoudadel2** [comment]
Hi,
I've added the license info:
https://github.com/mahmoudadel2/pysed/commit/9526acaef294b70fbb9ce00c5d59d64ea6518432
https://github.com/mahmoudadel2/pysed/commit/9ef7ae4155d6427c417fe50c69872487775e97bb
